track_id = "aaaa-aaaa-aaaa"
title = "Wolke alskdjfalsdj falskdjfl asdjfa asdf"
soundcloud = "https://soundcloud.com/user-22791579/wolke/s-O2fvvecs7c2"
bandcamp = "https://streampunk.bandcamp.com/track/wolke"

[counts]
view = 676
play = 52
download = 10
