track_id = "aaaa-aaaa-aaaa"
title = "Wolke"
soundcloud = "https://soundcloud.com/user-22791579/wolke/s-O2fvvecs7c2"
bandcamp = "https://streampunk.bandcamp.com/track/wolke"

[counts]
view = 978
play = 56
download = 11
