track_id = "AAAA-AAAA-AAAA"
title = "Wolke"
soundcloud = "https://soundcloud.com/user-22791579/wolke/s-O2fvvecs7c2"
bandcamp = "https://streampunk.bandcamp.com/track/wolke"

[counts]
view = 982
play = 57
download = 11
